export const propertyCategories = [
  { value: 'apartment', label: 'Apartment' },
  { value: 'house', label: 'House' },
  { value: 'villa', label: 'Villa' },
  { value: 'condo', label: 'Condo' },
  { value: 'cottage', label: 'Cottage' },
  { value: 'penthouse', label: 'Penthouse' },
  { value: 'loft', label: 'Loft' },
  { value: 'studio', label: 'Studio' },
  { value: 'bungalow', label: 'Bungalow' },
  { value: 'duplex', label: 'Duplex' },
  { value: 'townhouse', label: 'Townhouse' },
  { value: 'chalet', label: 'Chalet' },
  { value: 'farmhouse', label: 'Farmhouse' },
  { value: 'mobile-home', label: 'Mobile Home' },
  { value: 'ranch', label: 'Ranch' },
  { value: 'caravan', label: 'Caravan' },
  { value: 'cabin', label: 'Cabin' },
  { value: 'guesthouse', label: 'Guesthouse' },
  { value: 'mansion', label: 'Mansion' },
  { value: 'tiny-house', label: 'Tiny House' },
]

export const propertyFacilities = [
  { value: 'wifi', label: 'Wi-Fi' },
  { value: 'parking', label: 'Parking' },
  { value: 'air-conditioning', label: 'Air Conditioning' },
  { value: 'swimming-pool', label: 'Swimming Pool' },
  { value: 'gym', label: 'Gym' },
  { value: 'pet-friendly', label: 'Pet Friendly' },
  { value: 'laundry', label: 'Laundry' },
  { value: 'kitchen', label: 'Kitchen' },
  { value: 'tv', label: 'Television' },
  { value: 'breakfast-included', label: 'Breakfast Included' },
  { value: 'elevator', label: 'Elevator' },
  { value: 'balcony', label: 'Balcony' },
  { value: 'spa', label: 'Spa' },
  { value: 'sauna', label: 'Sauna' },
  { value: 'fireplace', label: 'Fireplace' },
  { value: 'barbecue', label: 'Barbecue' },
  { value: 'security', label: '24/7 Security' },
  { value: 'wheelchair-accessible', label: 'Wheelchair Accessible' },
  { value: 'garden', label: 'Garden' },
  { value: 'hot-tub', label: 'Hot Tub' },
]

export const propertyLocation = [
  { value: 'new-york', label: 'New York' },
  { value: 'los-angeles', label: 'Los Angeles' },
  { value: 'san-francisco', label: 'San Francisco' },
  { value: 'miami', label: 'Miami' },
  { value: 'chicago', label: 'Chicago' },
  { value: 'seattle', label: 'Seattle' },
  { value: 'boston', label: 'Boston' },
  { value: 'las-vegas', label: 'Las Vegas' },
  { value: 'washington-dc', label: 'Washington D.C.' },
  { value: 'orlando', label: 'Orlando' },
  { value: 'denver', label: 'Denver' },
  { value: 'houston', label: 'Houston' },
  { value: 'philadelphia', label: 'Philadelphia' },
  { value: 'san-diego', label: 'San Diego' },
  { value: 'dallas', label: 'Dallas' },
  { value: 'atlanta', label: 'Atlanta' },
  { value: 'austin', label: 'Austin' },
  { value: 'phoenix', label: 'Phoenix' },
  { value: 'portland', label: 'Portland' },
  { value: 'tampa', label: 'Tampa' },
]

export const guestPlaceTypes = [
  { value: 'entire_place', label: 'An entire place' },
  { value: 'private_room', label: 'A room' },
]

export const incrementType = [
  { value: 'percentage', label: '%: add price by percentage' },
  { value: 'amount', label: 'Amount: add price by adding amount' },
]

export const propertyList = [
  {
    imageSrc: [
      'https://dummyimage.com/300x200/000/fff',
      'https://dummyimage.com/400x300/00ff00/000',
      'https://dummyimage.com/600x400/0000ff/fff',
    ],
    location: 'Nusa Ceningan, Indonesia',
    description: 'On the beach',
    dateRange: 'Apr 7 - 12',
    pricePerNight: 'Rp2,250,000',
    rating: 4.83,
  },
  {
    imageSrc: [
      'https://dummyimage.com/300x200/000/fff',
      'https://dummyimage.com/400x300/00ff00/000',
      'https://dummyimage.com/600x400/0000ff/fff',
    ],
    location: 'Nusa Ceningan, Indonesia',
    description: 'On the beach',
    dateRange: 'Apr 7 - 12',
    pricePerNight: 'Rp2,250,000',
    rating: 4.83,
  },
  {
    imageSrc: [
      'https://dummyimage.com/300x200/000/fff',
      'https://dummyimage.com/400x300/00ff00/000',
      'https://dummyimage.com/600x400/0000ff/fff',
    ],
    location: 'Nusa Ceningan, Indonesia',
    description: 'On the beach',
    dateRange: 'Apr 7 - 12',
    pricePerNight: 'Rp2,250,000',
    rating: 4.83,
  },
  {
    imageSrc: [
      'https://dummyimage.com/300x200/000/fff',
      'https://dummyimage.com/400x300/00ff00/000',
      'https://dummyimage.com/600x400/0000ff/fff',
    ],
    location: 'Dieng, Indonesia',
    description: 'On the beach',
    dateRange: 'Apr 7 - 12',
    pricePerNight: 'Rp2,250,000',
    rating: 4.83,
  },
  {
    imageSrc: [
      'https://dummyimage.com/300x200/000/fff',
      'https://dummyimage.com/400x300/00ff00/000',
      'https://dummyimage.com/600x400/0000ff/fff',
    ],
    location: 'Yogyakarta, Indonesia',
    description: 'On the beach',
    dateRange: 'Apr 7 - 12',
    pricePerNight: 'Rp2,250,000',
    rating: 4.83,
  },
  {
    imageSrc: [
      'https://dummyimage.com/300x200/000/fff',
      'https://dummyimage.com/400x300/00ff00/000',
      'https://dummyimage.com/600x400/0000ff/fff',
    ],
    location: 'Bandung, Indonesia',
    description: 'On the beach',
    dateRange: 'Apr 7 - 12',
    pricePerNight: 'Rp2,250,000',
    rating: 4.83,
  },
  {
    imageSrc: [
      'https://dummyimage.com/300x200/000/fff',
      'https://dummyimage.com/400x300/00ff00/000',
      'https://dummyimage.com/600x400/0000ff/fff',
    ],
    location: 'Bali, Indonesia',
    description: 'On the beach',
    dateRange: 'Apr 7 - 12',
    pricePerNight: 'Rp2,250,000',
    rating: 4.83,
  },
]
